# FROM almalinux:9
# # CMD ["ping", "google.com"]
# ENTRYPOINT ["ping", "google.com"]

# FROM almalinux:9
# # CMD ["ping", "google.com"]
# ENTRYPOINT ["ping", "google.com"]

FROM almalinux:9
CMM ["google.com"]
ENTRYPOINT ["ping"]
